__default__:
  project: acc_MMAAAS
  queue: premium
  cores: 4
  mem: 250
  himem: ''
  time: '00:30'
revertsam:
  time: ' 02:00'
sortsam:
  mem: 1500
  time: '01:00'
collect_quality_yield_metrics:
  mem: 1000
align_bam_bwa:
  mem: 2500
  time: '08:00'
mark_duplicates:
  time: '08:00'
  cores: 5
  mem: 8000
sort_bam:
  time: '02:00'
  mem: '100000'
  cores: 4
#  himem: '-R himem'
crosscheck_fingerprints:
  time: '09:00'
base_recalibrator_report:
  mem: 800
apply_bqsr:
  mem: 800
collect_aggregated_metrics:
  time: '05:00'
collect_wgs_metrics:
  time: '05:00'
collect_raw_wgs_metrics:
  time: '05:00'
convert_to_cram:
  time: '06:00'
validate_cram:
  time: '3:45'
import_gvcfs:
  mem: 1500
  time: '02:00'
genotype_gvcfs:
  time: '3:00'
  mem: 2000
  cores: 3 
hard_filter_make_sites_only_vcf:
  time: '5:00'
indel_variant_recal:
  mem: 2500
snp_variant_recal_classic_if_numgvcf_lessthan_equalto_snp_recal_thresh20000:
  mem: 3000
apply_recal:
  mem: 800
collect_final_variant_calling_metrics:
  mem: 1000
  time: '01:00'
crosscheck_fingerprints_solo:
  mem: 800
