__default__:
  project: acc_MMAAAS
  queue: premium
  cores: 4
  mem: 250
  himem: ''
  time: '00:30'
revertsam:
  mem: 2000
  time: '04:00'
sortsam:
  mem: 8000
  time: '01:30'
collect_quality_yield_metrics:
  mem: 1000
align_bam_bwa:
  mem: 8000
  time: '09:00'
mark_duplicates:
  time: '08:00'
  cores: 6
  mem: 10000
sort_bam:
  time: '04:00'
  mem: '100000'
  cores: 4
#  himem: '-R himem'
check_contamination:
  time: '01:00'
crosscheck_fingerprints:
  time: '09:00'
base_recalibrator_report:
  mem: 800
  time: '1:30'
gather_bqsr_reports:
  mem: 500
  time: '02:00'
apply_bqsr:
  mem: 800
gather_recal_bams:
  time: '02:00'
collect_rg_bam_metrics:
  mem: 1500
  time: '04:00'
collect_aggregated_metrics:
  time: '06:00'
  mem: 1750
collect_wgs_metrics:
  time: '05:00'
  mem: 750
collect_raw_wgs_metrics:
  time: '05:00'
  mem: 750
convert_to_cram:
  time: '06:00'
validate_cram:
  time: '3:45'
  mem: 750
gatk4_haplotype_caller:
  mem: 1000
  time: '03:00'
merge_interval_gvcfs:
  mem: 500
  time: '01:00'
validate_gvcf:
  mem: 750
  time: '01:00'
collect_variant_calling_metrics:
  mem: 500
  time: '01:30'
import_gvcfs:
  mem: 3000
  time: '02:00'
genotype_gvcfs:
  time: '3:00'
  mem: 4500
  cores: 4 
hard_filter_make_sites_only_vcf:
  mem: 500
  time: '5:00'
indel_variant_recal:
  mem: 2500
snp_variant_recal_classic_if_numgvcf_lessthan_equalto_snp_recal_thresh20000:
  mem: 3000
apply_recal:
  mem: 2000
collect_final_variant_calling_metrics:
  mem: 1000
  time: '01:00'
crosscheck_fingerprints_solo:
  mem: 1000
