
### resources ###
AXIOMPOLY_RESOURCE_VCF: resources/hg38/v0/references-hg38-v0-Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
BATCH_SIZE: 50
BREAK_BANDS_AT_MULTIPLES_OF: 1000000
BWA_VERSION: 0.7.8-r455
#[minerg01@li03c03 ~]$ ml bwa/0.7.8
##[minerg01@li03c03 ~]$ BWA_VERSION=$(bwa 2>&1 |     grep -e '^Version' |     sed 's/Version: //')
##[minerg01@li03c03 ~]$ echo $BWA_VERSION
##0.7.8-r455

CALLING_INTERVAL_LIST: resources/hg38/v0/resources-broad-hg38-v0-wgs_calling_regions.hg38.interval_list
CALLSET_NAME: aaa_cohort_20220201
COMPRESSION_LEVEL: 2
# CONTAMINATION_SITES_BED: resources/hg38/v0/references-hg38-v0-Homo_sapiens_assembly38.contam.bed
# CONTAMINATION_SITES_MU: resources/hg38/v0/references-hg38-v0-Homo_sapiens_assembly38.contam.mu
# CONTAMINATION_SITES_UD: resources/hg38/v0/references-hg38-v0-Homo_sapiens_assembly38.contam.UD
CONTAMINATION_SITES_PREFIX: resources/hg38/v0/references-hg38-v0-Homo_sapiens_assembly38.contam
CONTAMINATION_UNDERESTIMATION_FACTOR: 0.75
CROSSCHECK_BY: READGROUP
DBSNP_VCF: resources/hg38/v0/resources-broad-hg38-v0-Homo_sapiens_assembly38.dbsnp138.vcf
EVALUATION_INTERVAL_LIST: resources/hg38/v0/intervals_wgs_evaluation_regions.hg38.interval_list
# ExcessHet is a phred-scaled p-value. We want a cutoff of anything more extreme
# than a z-score of -4.5 which is a p-value of 3.4e-06, which phred-scaled is 54.69  
EXCESS_HET_THRESHOLD: 54.69
GENOTYPES_FINGERPRINT_FILE: resources/hg38/v0/NA12878_NA12878.hg38.reference.fingerprint.vcf
HAPLOTYPE_DATABASE_FILE: resources/hg38/v0/references-hg38-v0-Homo_sapiens_assembly38.haplotype_database.txt
HAPLOTYPE_SCATTER_COUNT: 50
HAPMAP_RESOURCE_VCF: resources/hg38/v0/resources-broad-hg38-v0-hapmap_3.3.hg38.vcf.gz
INDEL_FILTER_LEVEL: 99.0
INDEL_MAX_GAUSSIANS: 4
INDEL_RECALIBRATION_ANNOTATION_VALUES:  ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
INDEL_RECALIBRATION_TRANCHE_VALUES: ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
KNOWN_SITES_HOMOSAPIENS: resources/hg38/v0/resources-broad-hg38-v0-Homo_sapiens_assembly38.known_indels.vcf.gz
KNOWN_SITES_MILLS1000G: resources/hg38/v0/resources-broad-hg38-v0-Mills_and_1000G_gold_standard.indels.hg38.vcf.gz

LOD_THRESHOLD: -20.0

MAX_CHIMERISM_IN_REASONABLE_SAMPLE: 0.15
MAX_DUPLICATION_IN_REASONABLE_SAMPLE: 0.30
OMNI_RESOURCE_VCF: resources/hg38/v0/resources-broad-hg38-v0-1000G_omni2.5.hg38.vcf.gz

ONE_THOUSAND_GENOMES_RESOURCE_VCF: resources/hg38/v0/resources-broad-hg38-v0-1000G_phase1.snps.high_confidence.hg38.vcf.gz

READ_LENGTH: 250
REF_DICT: resources/hg38/v0/resources-broad-hg38-v0-Homo_sapiens_assembly38.dict
REF_FASTA: resources/hg38/v0/resources-broad-hg38-v0-Homo_sapiens_assembly38.fasta
SAMPLE_NAME: NA12878
SAMPLE_NUM_THRESHOLD: 2
SCATTER_MODE: BALANCING_WITHOUT_INTERVAL_SUBDIVISION_WITH_OVERFLOW
SNP_FILTER_LEVEL: 99.7
SNP_MAX_GAUSSIANS: 6
SNP_RECALIBRATION_ANNOTATION_VALUES: ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]
SNP_RECALIBRATION_TRANCHE_VALUES: ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0"]

UNBOUNDED_SCATTER_COUNT_SCALE_FACTOR: 2.5
UNPADDED_INTERVAL_FILE: resources/hg38/v0/intervals-hg38.even.handcurated.20k.intervals
VerifyBamID: /sc/arion/projects/MMAAAS/src/VerifyBamID/bin/VerifyBamID
# downloaded and compiled usiing : git clone https://github.com/Griffan/VerifyBamID.git
# cd VerifyBamID \ mkdir build \ cd build \ cmake .. \ make \make test 
# then add bin file to .bashrc Path
WGS_COVERAGE_INTERVAL_LIST: resources/hg38/v0/intervals_wgs_coverage_regions.hg38.interval_list
############################################################################

##PICARD: /hpc/users/marcoe02/src/picard/picard.jar
#SNPEFF: /sc/orga/projects/MMAAAS/src/snpeff/snpEff/snpEff.jar
#SNPEFFc: /hpc/users/minerg01/src/snpEff/snpEff.config
#SNPSIFT: /sc/orga/projects/MMAAAS/src/snpeff/snpEff/SnpSift.jar
##DBNSFP: /sc/orga/projects/MMAAAS/src/dbNSFP/dbNSFPv3/hg19/dbNSFP3.5a_hg19.txt.gz
#DBNSFP: /sc/orga/projects/MMAAAS/src/dbNSFP/dbNSFPv2.9/dbNSFP2.9.txt.gz
#GNOMAD: /sc/orga/projects/MMAAAS/gnomad_data/vcf/genomes
#MAGMA: /sc/orga/projects/MMAAAS/src/magma_v1.06b/magma
#
#GENOME: GRCh37.75

#PHENO_COVARS_ALL: input/pheno_covars/adsp.pv.wes.nhw_ind.apoe_all.10418.pheno_covars.tsv
#PHENO_COVARS_EXTREMES: input/pheno_covars/adsp.pv.wes.nhw_ind.apoe33_extremes.2606.pheno_covars.tsv
#COVAR_NAMES: PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,SCBroad,SCWashU

##STRATUM: apoe33_extremes
#NIND: 243
#MAC_MIN: 0 # applies to single analyses only!
#MAF_MAX: 1 # applies to burden/kernel analyses only!

#SMALL_DISK: 100
#MEDIUM_DISK: 200
#LARGE_DISK: 1000
#HUGE_DISK: 2000
